### ISSUE TITLE
Faster RCNN in TF serving

### ISSUE THREAD

**Issue by vaklyuenkov** [markusnagel/CVPR2015-markus#1]
Hello! I apologize for bothering you here, but it seems like you are the only one, who can help. 
I try to serve Faster RCNN in TF serving and can't find how to avoid using PyFunc or serve them.
https://github.com/endernewton/tf-faster-rcnn/issues/113#issuecomment-306112530

I'll be very grateful you for any idea!

**Comment by markusnagel** [comment]
Not related to this repo, I replied in the correct issue.
